/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.0.1/userguide/multi_project_builds.html
 */

rootProject.name = "dialector"

include("dialector-kt")
include("dialector-kt-gradle")
include("dialector-kt-processor")
include("glottony")
include("glottony:server")
include("glottony:client")

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            when (requested.id.id) {
                "symbol-processing" ->
                    useModule("com.google.devtools.ksp:symbol-processing:${requested.version}")
            }
        }
    }

    repositories {
        gradlePluginPortal()
        google()
    }
}