[versions]
dokkaVersion = "2.2.0"
hamkrestVersion = "1.8.0.1"
gradleMavenPublishVersion = "0.37.0"
junitVersion = "6.1.3"
kotlinCompileTestingVersion = "0.13.0"
kotlinVersion = "2.4.10"
kspVersion = "2.3.11"
kotlinLoggingVersion = "8.0.4"
kotlinPoetVersion = "2.3.0"
kotlinterVersion = "5.7.0"
kotlinxCoroutinesVersion = "1.11.0"
koverVersion = "0.9.9"
ktlintVersion = "1.8.0"
lsp4jVersion = "1.0.0"
mockkVersion = "1.14.11"
slf4jVersion = "2.0.18"

[libraries]
hamkrest = { module = "com.natpryce:hamkrest", version.ref = "hamkrestVersion" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlinCompileTestingVersion" }
kotlin-compile-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kotlinCompileTestingVersion" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLoggingVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinVersion" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlinVersion" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoetVersion" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoetVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesVersion" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinxCoroutinesVersion" }
#ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlintVersion" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlintVersion" }
ktlint-ruleset-standard = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlintVersion" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspVersion" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4jVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jVersion" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradleMavenPublishVersion"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinterVersion" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "koverVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
