package dev.dialector.syntax

/**
 * Annotated classes are part of the Dialector model constructor DSL. Generally this will be used on methods
 * generated by the KSP processor.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
@DslMarker
public annotation class ModelConstructorDsl

/**
 * Indicates that the target class defines the structure of a [Node]
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.CLASS)
public annotation class NodeDefinition(
    /**
     * Determines whether this node should be instantiable or not.
     */
    val abstract: Boolean = false,
)

/**
 * Represents a non-node property of this node.
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.PROPERTY)
public annotation class Property(
    /**
     * Indicates that this property has a default value defined. A generated builder
     * use the default if no value was assigned.
     */
    val hasDefault: Boolean = false,
)

/**
 * Represents a child of this node.
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.PROPERTY)
public annotation class Child

/**
 * Represents a reference to another node in the model.
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.PROPERTY)
public annotation class Reference
