name: Snapshot From Main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository -Pversion=${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: '**/test-results/test/*.xml'
          reporter: java-junit