name: pull-request-build
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and Test
        run: ./gradlew build

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit

      - name: Coverage Report
        uses: mi-kas/kover-report@v1
        with:
          path: '${{ github.workspace }}/build/reports/kover/report.xml'
          title: Coverage Results
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
