name: Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToOSSRHRepository -Pversion=${{ github.event.release.tag_name }}
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_USERNAME }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: '**/test-results/test/*.xml'
          reporter: java-junit